name: Count words in all Markdown files

description: Action for counting words in all Markdown files within a given repository.

inputs:
  root_dir:
    description: 'Root repo where results are saved and shared from.'
    required: true
  courses_dir:
    description: 'Directory of interest where we will count words in all Markdown files.'
    required: true
  python_version:
    description: 'Python version to use for running the script.'
    required: false
    default: '3.13'

runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - name: Count words in Markdown files
      shell: bash
      run: |
        echo "::notice::Running count-words python script directly from workflow job 'main'..."
        python .github/actions/count-words/wc.py ${{ inputs.root_dir  }} ${{ inputs.courses_dir  }}
        echo "::notice::Finished. Results are saved in 'results.md'."

    - name: Upload results to Step Summary
      shell: bash
      run: |
        echo "::notice::Pushing results to Step Summary..."
        cat results.md >> $GITHUB_STEP_SUMMARY
        echo "::notice::Finished. Results are available in the Step Summary."

    - name: Get job URL and total WC
      shell: bash
      run: |
        echo "::notice::Grabbing job URL."
        URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT
        echo "::notice::Finished. Job Step Summary is available at $URL"
        echo "::notice::Total wordcount: $(cat totals.txt)"
        echo "{url}={$URL}" >> $GITHUB_OUTPUT
        echo "{wordcount}=$(cat totals.txt)" >> $GITHUB_OUTPUT
